<Project>
	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>preview</LangVersion>
		<AnalysisLevel>preview-all</AnalysisLevel>
		<AnalysisMode>All</AnalysisMode>
		<SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
		<UseArtifactsOutput>true</UseArtifactsOutput>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn>
	</PropertyGroup>
</Project>
