<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>CLI</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Spectre.Console.Cli" />
		<PackageReference Include="SSH.NET" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\Services\Azure\Azure.csproj" />
		<ProjectReference Include="..\Services\Google\Google.csproj" />
		<ProjectReference Include="..\Services\LastFm\LastFm.csproj" />
		<ProjectReference Include="..\Services\Audio\Audio.csproj" />
	</ItemGroup>
</Project>
