<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>SacdProbe</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\Services\Audio\Audio.csproj" />
		<ProjectReference Include="..\..\src\Core\Core.csproj" />
	</ItemGroup>
</Project>
