<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Spectre.Console.Cli.Extensions.DependencyInjection" />
		<PackageReference Include="DotNetEnv" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\CLI\CLI.csproj" />
		<ProjectReference Include="..\Core\Core.csproj" />
		<ProjectReference Include="..\Services\Pristine\Pristine.csproj" />
	</ItemGroup>

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<RootNamespace>App</RootNamespace>
	</PropertyGroup>
</Project>
