<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="ErrorOr" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Serilog.Formatting.Compact" />
		<PackageReference Include="Serilog.Sinks.File" />
		<PackageReference Include="Serilog.Sinks.Seq" />
		<PackageReference Include="Serilog.Sinks.Spectre" />
		<PackageReference Include="SerilogTracing" />
		<PackageReference Include="Spectre.Console" />
		<PackageReference Include="SSH.NET" />
	</ItemGroup>
</Project>
